import streamlit as st
import pandas as pd
from pathlib import Path
import numpy as np

# Set page config
st.set_page_config(page_title="Logistics Data Quality Dashboard", layout="wide", page_icon="🚢")

# --- Constants & Paths ---
DATA_DIR = Path("data/synthetic")
PROCESSED_DIR = Path("data/processed")

DIRTY_DATA_PATH = DATA_DIR / "shipping_manifests_dirty.csv"
RULE_FINDINGS_PATH = PROCESSED_DIR / "rule_based_validation_findings.csv"
ML_FINDINGS_PATH = PROCESSED_DIR / "ml_baseline_validation_findings.csv"

# --- Data Loading ---
@st.cache_data
def load_data():
    try:
        dirty_df = pd.read_csv(DIRTY_DATA_PATH)
        rule_findings = pd.read_csv(RULE_FINDINGS_PATH)
        
        # Load ML findings if they exist
        if ML_FINDINGS_PATH.exists():
            ml_findings = pd.read_csv(ML_FINDINGS_PATH)
            # Combine findings
            all_findings = pd.concat([rule_findings, ml_findings], ignore_index=True)
        else:
            all_findings = rule_findings
            
        return dirty_df, all_findings
    except FileNotFoundError as e:
        st.error(f"Error loading data. Have you run the generation and validation scripts? Details: {e}")
        return pd.DataFrame(), pd.DataFrame()

# --- Utility Functions ---
def apply_color(val):
    if val == "critical":
        return 'background-color: darkred; color: white'
    elif val == "high":
        return 'background-color: red; color: white'
    elif val == "medium":
        return 'background-color: orange; color: black'
    elif val == "low":
        return 'background-color: yellow; color: black'
    return ''

# --- Main App ---
def main():
    st.title("🚢 Customs & Logistics Data Quality Dashboard")
    st.markdown("""
    **Human-in-the-Loop Exception Management System**
    
    This dashboard simulates the workflow of a customs reviewer. The system automatically scans incoming manifests using both **Deterministic Rules** and **Machine Learning Models** (NLP/Anomaly Detection) to flag high-risk shipments for manual review.
    """)
    
    dirty_df, findings_df = load_data()
    
    if dirty_df.empty or findings_df.empty:
        st.stop()

    # --- Sidebar Filters ---
    st.sidebar.header("Filter Review Queue")
    
    severity_filter = st.sidebar.multiselect(
        "Severity Level",
        options=["critical", "high", "medium", "low"],
        default=["critical", "high"]
    )
    
    rule_type_filter = st.sidebar.multiselect(
        "Detection Source",
        options=findings_df['rule_name'].unique(),
        default=findings_df['rule_name'].unique().tolist()
    )
    
    # Filter the findings
    filtered_findings = findings_df[
        findings_df['severity'].isin(severity_filter) & 
        findings_df['rule_name'].isin(rule_type_filter)
    ]
    
    # Get the unique manifests that have issues
    manifests_with_issues = filtered_findings['manifest_id'].unique()
    
    # Metrics
    st.markdown("### 📊 Operational Overview")
    col1, col2, col3, col4 = st.columns(4)
    
    total_manifests = len(dirty_df)
    flagged_manifests = len(findings_df['manifest_id'].unique())
    auto_cleared = total_manifests - flagged_manifests
    auto_cleared_pct = (auto_cleared / total_manifests) * 100 if total_manifests > 0 else 0
    
    col1.metric("Total Manifests Today", f"{total_manifests:,}")
    col2.metric("Auto-Cleared (Low Risk)", f"{auto_cleared:,}", f"{auto_cleared_pct:.1f}%")
    col3.metric("Requires Manual Review", f"{flagged_manifests:,}", f"-{auto_cleared_pct:.1f}% Workload", delta_color="inverse")
    col4.metric("Current Queue Size", f"{len(manifests_with_issues):,}")

    st.markdown("---")
    
    # --- Review Queue ---
    st.markdown("### 📋 Active Review Queue")
    st.write(f"Showing **{len(manifests_with_issues)}** manifests matching filter criteria.")
    
    if len(manifests_with_issues) == 0:
        st.success("Queue is empty for the selected filters! 🎉")
    else:
        # Create an interactive selection for the queue
        selected_manifest = st.selectbox("Select a Manifest to Review:", manifests_with_issues)
        
        if selected_manifest:
            st.markdown("#### 🔍 Review Details")
            
            # 1. Show the specific flags for this manifest
            st.subheader("Flags Generated by System")
            manifest_flags = findings_df[findings_df['manifest_id'] == selected_manifest]
            
            # Format and display
            display_cols = ['severity', 'rule_name', 'affected_field', 'observed_value', 'detection_message', 'recommended_action']
            st.dataframe(manifest_flags[display_cols].style.map(apply_color, subset=['severity']), use_container_width=True)
            
            # 2. Show the raw record context
            st.subheader("Original Manifest Record")
            manifest_record = dirty_df[dirty_df['manifest_id'] == selected_manifest]
            st.dataframe(manifest_record, use_container_width=True)
            
            # 3. Action Buttons
            colA, colB, colC = st.columns(3)
            colA.button("✅ Approve (Override System)", use_container_width=True, type="primary")
            colB.button("✉️ Request Revision from Submitter", use_container_width=True)
            colC.button("🛑 Reject Shipment", use_container_width=True)
            

if __name__ == "__main__":
    main()
